#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""终端帮助文本打印。"""


def print_help(n_joints):
    print("\n" + "-" * 66)
    print("  键盘操作帮助")
    print("-" * 66)
    print("  1-%d        选择关节" % min(n_joints, 9))
    print("  ← / →      减小 / 增大当前关节角 (单步)")
    print("  ↑ / ↓      大步减小 / 增大当前关节角 (5x)")
    print("  [ / ]      上一个 / 下一个关节")
    print("  e          编辑当前关节 (键入数值)")
    print("  g          展开/收起右侧设置面板")
    print("  r          所有关节归零")
    print("  c          打印当前关节角")
    print("  h          显示帮助")
    print("  q / ESC    退出")
    print("-" * 66)
    print("  悬浮输入面板 (窗口内, 左上):")
    print("    点击关节行  进入编辑, 键入数值")
    print("    Enter       应用输入并钳制到限位")
    print("    Tab         切换 rad / deg 单位")
    print("    Esc         取消编辑")
    print("    拖拽关节行  像滑条一样连续调节角度")
    print("-" * 66)
    print("  右侧设置面板 (g 键或点击右缘 [<] 竖条):")
    print("    == SETTINGS == 行  点 [>] hide 收起面板")
    print("    AXIS SIZE   拖拽该行调世界坐标轴大小")
    print("    VIEW        点 Front/Side/Top/Iso 切换预设视角, Reset 重置")
    print("    JOINT FRAMES 点各行开/关对应关节坐标系")
    print("    LINKS       点各行开/关对应连杆可见度")
    print("-" * 66)
    print("  字体缩放: --ui-scale N (默认 0=按窗口高度自动, 4K 约 2x)")
    print("-" * 66)
    print("  鼠标视角控制 (在面板区域之外):")
    print("    左键拖拽    旋转视角")
    print("    中键拖拽    平移视角 (pan)")
    print("    右键拖拽    缩放")
    print("    滚轮        缩放")
    print("    Shift+左键  平移  Ctrl+左键 翻滚  Ctrl+Shift+左键 缩放")
    print("-" * 66)
